Stable diffusion distributed training on EKS
aws-samples/awsome-distributed-training pull request #135
Opened 2024-02-09 00:38 UTC by awsankur

Added a section on how to run distributed training with EKS for stable diffusion

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-09 00:58 UTC, KeitaW reviewed
Great work!

2024-02-09 00:58 UTC, KeitaW commented on 3.test_cases/6.stable-diffusion/multi-node/3.stable-diffusion-eks.yaml-template
> +              #- name: FI_EFA_USE_DEVICE_RDMA
I believe that those values are not necessary. So safe to remove?

2024-02-09 00:58 UTC, KeitaW commented on 3.test_cases/6.stable-diffusion/README.md
> +
It would be great if we could have some guidance on how to destroy the P5 managed node group.

2024-02-18 15:28 UTC, awsankur commented on 3.test_cases/6.stable-diffusion/README.md
> +
done

2024-02-18 17:05 UTC, iankouls-aws requested changes
Great work!
A couple of minor changes noted in comments.
Also please include instructions to deploy the Kubeflow training operator to the cluster as this is a prerequisite (unless it is already there and I missed it).
I believe after addressing these comments, the PR is ready to merge.

2024-02-18 17:05 UTC, iankouls-aws commented on 3.test_cases/6.stable-diffusion/README.md
> +Once the nodes are created, you can use `nv` to list the available nodes. `nv` is an alias to `eks-node-viewer` . You can see other aliases by typing `alias`. Below is a sample output with a cluster
The statement that you should terminate `Not Ready` nodes from the console so they would become ready might lead to confusion here. I think you are referring to the case when you have P5 nodes that become NotReady during operation (like when they experience hardware failures, ECC errors, etc.) and the way to get them back is to restart them or terminate them so EKS gets new ones. Have you seen c5 instances be in NotReady state for long?
When nodes are joining the cluster, it is expected that they would be in NotReady state first, and when they finish initializing, will transition to Ready state. I am afraid this statement would tell people to terminate nodes while they are initializing, which will be counterproductive as they would be fighting against the normal operation of the cluster.

2024-02-18 17:05 UTC, iankouls-aws commented on 3.test_cases/6.stable-diffusion/multi-node/3.stable-diffusion-eks.yaml-template
> +              # for P5 FI_* should be commented out
This comment line is unnecessary since you've already removed all the FI_ env variables from the manifest

2024-02-20 16:47 UTC, mhuguesaws commented on 3.test_cases/6.stable-diffusion/multi-node/3.stable-diffusion-eks.yaml-template
> +          #nodeSelector:
remove

2024-02-20 16:47 UTC, mhuguesaws commented on 3.test_cases/6.stable-diffusion/multi-node/3.stable-diffusion-eks.yaml-template
> +                  nvidia.com/gpu:
specify gpu type

2024-02-21 05:44 UTC, awsankur commented on 3.test_cases/6.stable-diffusion/README.md
> +Once the nodes are created, you can use `nv` to list the available nodes. `nv` is an alias to `eks-node-viewer` . You can see other aliases by typing `alias`. Below is a sample output with a cluster
Good point. Will remove this line for clarity.

2024-02-21 05:59 UTC, merged