Bionemo
aws-samples/awsome-distributed-training pull request #143
Opened 2024-02-17 00:49 UTC by awsankur

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-18 04:53 UTC, KeitaW requested changes
Great work! 
I had small hiccups I want to check with you.
1. I tried the test case on PCluster (AMI built from the latest DLAMI), and got  the following at step 8 (Download and preprocess data). 
```
0: /usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 2.22.1ubuntu1 is an invalid version and will not be supported in a future release
0:   warnings.warn(
0: NOTE! Installing ujson may make loading annotations faster.
0: Traceback (most recent call last):
0:   File "/workspace/bionemo/prepare_uniref50.py", line 1, in <module>
0:     from bionemo.data import UniRef50Preprocess
0:   File "/workspace/bionemo/bionemo/data/__init__.py", line 13, in <module>
0:     from .molecule import *
0:   File "/workspace/bionemo/bionemo/data/molecule/__init__.py", line 12, in <module>
0:     from .csv_dataset import *
0:   File "/workspace/bionemo/bionemo/data/molecule/csv_dataset.py", line 14, in <module>
0:     from nemo.collections.nlp.data.language_modeling.megatron.dataset_utils import (
0:   File "/usr/local/lib/python3.10/dist-packages/nemo/collections/nlp/__init__.py", line 15, in <module>
0:     from nemo.collections.nlp import data, losses, models, modules
0:   File "/usr/local/lib/python3.10/dist-packages/nemo/collections/nlp/models/__init__.py", line 37, in <module>
0:     from nemo.collections.nlp.models.token_classification import (
0:   File "/usr/local/lib/python3.10/dist-packages/nemo/collections/nlp/models/token_classification/__init__.py", line 14, in <module>
0:     from nemo.collections.nlp.models.token_classification.punctuation_capitalization_config import (
0:   File "/usr/local/lib/python3.10/dist-packages/nemo/collections/nlp/models/token_classification/punctuation_capitalization_config.py", line 21, in <module>
0:     from nemo.collections.nlp.data.token_classification.punctuation_capitalization_dataset import (
0:   File "/usr/local/lib/python3.10/dist-packages/nemo/collections/nlp/data/token_classification/punctuation_capitalization_dataset.py", line 57, in <module>
0:     from nemo.collections.asr.parts.preprocessing import AudioSegment
0:   File "/usr/local/lib/python3.10/dist-packages/nemo/collections/asr/__init__.py", line 15, in <module>
0:     from nemo.collections.asr import data, losses, models, modules
0:   File "/usr/local/lib/python3.10/dist-packages/nemo/collections/asr/losses/__init__.py", line 16, in <module>
0:     from nemo.collections.asr.losses.audio_losses import SDRLoss
0:   File "/usr/local/lib/python3.10/dist-packages/nemo/collections/asr/losses/audio_losses.py", line 21, in <module>
0:     from nemo.collections.asr.parts.preprocessing.features import make_seq_mask_like
0:   File "/usr/local/lib/python3.10/dist-packages/nemo/collections/asr/parts/preprocessing/__init__.py", line 16, in <module>
0:     from nemo.collections.asr.parts.preprocessing.features import FeaturizerFactory, FilterbankFeatures, WaveformFeaturizer
0:   File "/usr/local/lib/python3.10/dist-packages/nemo/collections/asr/parts/preprocessing/features.py", line 39, in <module>
0:     import librosa
0:   File "/usr/local/lib/python3.10/dist-packages/librosa/__init__.py", line 209, in <module>
0:     from . import core
0:   File "/usr/local/lib/python3.10/dist-packages/librosa/core/__init__.py", line 5, in <module>
0:     from .convert import *  # pylint: disable=wildcard-import
0:   File "/usr/local/lib/python3.10/dist-packages/librosa/core/convert.py", line 7, in <module>
0:     from . import notation
0:   File "/usr/local/lib/python3.10/dist-packages/librosa/core/notation.py", line 8, in <module>
0:     from ..util.exceptions import ParameterError
0:   File "/usr/local/lib/python3.10/dist-packages/librosa/util/__init__.py", line 77, in <module>
0:     from .utils import *  # pylint: disable=wildcard-import
0:   File "/usr/local/lib/python3.10/dist-packages/librosa/util/utils.py", line 9, in <module>
0:     import numba
0:   File "/usr/local/lib/python3.10/dist-packages/numba/__init__.py", line 42, in <module>
0:     from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
0:   File "/usr/local/lib/python3.10/dist-packages/numba/np/ufunc/__init__.py", line 3, in <module>
0:     from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
0:   File "/usr/local/lib/python3.10/dist-packages/numba/np/ufunc/decorators.py", line 3, in <module>
0:     from numba.np.ufunc import _internal
0: SystemError: initialization of _internal failed without raising an exception
srun: error: p5-st-p5-1: task 0: Exited with exit code 1
```
probably due to the same reason as https://github.com/openai/whisper/discussions/1103. 
The error did not show up when I installed `numba` explicitly 

2. When I tried `1.uniref50.slurm` the preprocessing step takes long time. I wait three and half hours yet the job has not finished yet. Is this expected? Here is the log.
```
il -f slurm-uniref-21.out 
0: NOTE! Installing ujson may make loading annotations faster.
0: [NeMo I 2024-02-18 01:24:27 preprocess:289] Download and preprocess of UniRef50 data does not currently use GPU. Workstation or CPU-only instance recommended.
0: [NeMo I 2024-02-18 01:24:27 preprocess:115] Data processing can take an hour or more depending on system resources.
0: [NeMo I 2024-02-18 01:24:27 preprocess:117] Downloading file from https://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref50/uniref50.fasta.gz...
0: [NeMo I 2024-02-18 01:24:27 preprocess:75] Downloading file to /fsx/raw/uniref50.fasta.gz...
0: [NeMo I 2024-02-18 01:25:52 preprocess:89] Extracting file to /fsx/raw/uniref50.fasta...
0: [NeMo I 2024-02-18 01:28:39 preprocess:311] UniRef50 data processing complete.
0: [NeMo I 2024-02-18 01:28:39 preprocess:313] Indexing UniRef50 dataset.
0: [NeMo I 2024-02-18 01:30:29 preprocess:319] Writing processed dataset files to /fsx/processed...
0: [NeMo I 2024-02-18 01:30:29 preprocess:255] Creating train split...
```

2024-02-19 21:23 UTC, rpomaris commented on 3.test_cases/14.bionemo/README.md
> +1. Have a slurm based parallelcluster created with a FSx for Lustre filesystem mounted.
Add assumption for Ubuntu

2024-02-19 21:30 UTC, rpomaris commented on 3.test_cases/14.bionemo/README.md
> +## 4. Run container on Head Node [Optional]
Maybe move this to a "Troubleshooting" section at the bottom of the page

2024-02-19 21:32 UTC, rpomaris commented on 3.test_cases/14.bionemo/README.md
> +
We should remove the copy/paste button from this, or remove the code block altogether. Otherwise people will copy/paste it into the terminal.

2024-02-19 21:43 UTC, rpomaris commented on 3.test_cases/14.bionemo/README.md
> +
This needs to be done on each of the compute nodes, right? We should state this explicitly.

2024-02-20 07:17 UTC, sean-smith commented on 3.test_cases/14.bionemo/0.Dockerfile
> +ARG AWS_OFI_NCCL_VERSION=v1.7.3-aws
bump.

2024-02-20 07:17 UTC, sean-smith commented on 3.test_cases/14.bionemo/0.Dockerfile
> +ARG EFA_INSTALLER_VERSION=latest
pin the version explicitly to prevent from future breaking changes.

2024-02-20 07:17 UTC, sean-smith commented on 3.test_cases/14.bionemo/0.Dockerfile
> +RUN git clone https://github.com/NVIDIA/nccl-tests.git /opt/nccl-tests \
why do we need the NCCL Tests?

2024-02-20 07:17 UTC, sean-smith commented on 3.test_cases/14.bionemo/README.md
> +MegaMolBART
Make into markdown table. See https://www.tablesgenerator.com/markdown_tables

2024-02-20 07:17 UTC, sean-smith commented on 3.test_cases/14.bionemo/README.md
> +
Same here.

2024-02-20 07:17 UTC, sean-smith commented on 3.test_cases/14.bionemo/README.md
> +### 2.1 If you have created your cluster with [DLAMI](https://aws.amazon.com/machine-learning/amis/) or your custom AMI, please make sure `libnvidia-container cli` is installed. You can follow the in
This should be included in the pyxis/enroot install for SageMaker HyperPod FYI.

2024-02-20 15:02 UTC, mhuguesaws commented on 3.test_cases/14.bionemo/0.Dockerfile
> +ARG NCCL_VERSION=v2.18.5-1
```suggestion
ARG NCCL_VERSION=v2.18.6-1
```

2024-02-20 15:02 UTC, mhuguesaws commented on 3.test_cases/14.bionemo/0.Dockerfile
> +ARG AWS_OFI_NCCL_VERSION=v1.7.3-aws
```suggestion
ARG AWS_OFI_NCCL_VERSION=v1.7.4-aws
```

2024-02-20 15:03 UTC, mhuguesaws commented on 3.test_cases/14.bionemo/0.Dockerfile
> +ARG EFA_INSTALLER_VERSION=latest
```suggestion
ARG EFA_INSTALLER_VERSION=1.30.0
```

2024-02-20 15:04 UTC, mhuguesaws commented on 3.test_cases/14.bionemo/README.md
> +0. You have access to the bionemo container.You can get access to the container from NGC. You may also follow the instructions provided [here](https://docs.nvidia.com/bionemo-framework/latest/quickst
What is NGC?

2024-02-20 15:04 UTC, mhuguesaws reviewed
Left comments

2024-02-20 16:39 UTC, mhuguesaws commented on 3.test_cases/14.bionemo/0.Dockerfile
> +    && make \
Add make install.

2024-02-20 16:43 UTC, mhuguesaws commented on 3.test_cases/14.bionemo/0.Dockerfile
> +    && ./configure --prefix=/opt/aws-ofi-nccl/install \
The flags are incorrect, please use

`./configure --prefix=/opt/aws-ofi-nccl \
--with-mpi=/opt/amazon/openmpi \
--with-libfabric=/opt/amazon/efa \
--with-cuda=/usr/local/cuda \
--enable-platform-aws`

2024-02-20 16:45 UTC, mhuguesaws commented on 3.test_cases/14.bionemo/requirements.txt
> +dask
pin version

2024-02-20 16:46 UTC, mhuguesaws commented on 3.test_cases/14.bionemo/requirements.txt
> +huggingface_hub>=0.13.0
```suggestion
huggingface_hub>=0.13.0,<0.14.0
```

2024-02-20 16:46 UTC, mhuguesaws reviewed
left comments in line

2024-02-20 18:13 UTC, perifaws commented on 3.test_cases/14.bionemo/requirements.txt
> +huggingface_hub>=0.13.0
We need a fixed version for dask as well

2024-02-21 13:14 UTC, syedazi reviewed
left some comments in README

2024-02-22 17:18 UTC, awsankur commented on 3.test_cases/14.bionemo/README.md
> +wget -O miniconda.sh "https://repo.anaconda.com/miniconda/${MINICONDA_INSTALLER}.sh" \
Thanks Keita.
1. I tried this with Pcluster with the base ubuntu AMI. Did not have to install `numba`. @rpomaris saw a similar error as you and could resolve the error by installing `numba`. Will add `numba` to requirements.tx.
2. The training data does take a long time to process. I am working on accelerating it. Will push that change in another PR.
3. Good point on the conda env. Will mention that explicitly

2024-02-22 17:27 UTC, awsankur commented on 3.test_cases/14.bionemo/README.md
> +1. Install NGC CLI: https://ngc.nvidia.com/setup/installers/cli
Yeah I realized that you need to login to NGC Container Registry anymore

2024-02-22 18:27 UTC, awsankur commented on 3.test_cases/14.bionemo/README.md
> +1. Install NGC CLI: https://ngc.nvidia.com/setup/installers/cli
Yes I can pull this image now without logging to NGC Container Registry:

http://nvcr.io/nvidia/nemo:24.01.framework

2024-02-22 18:31 UTC, awsankur commented on 3.test_cases/14.bionemo/1.uniref50.slurm
> +#SBATCH --gpus-per-node=8
updated

2024-02-22 23:33 UTC, awsankur commented on 3.test_cases/14.bionemo/README.md
> +```bash
It does exist by default

2024-02-22 23:36 UTC, awsankur commented on 3.test_cases/14.bionemo/README.md
> +
No that depends on the user

2024-02-24 17:53 UTC, merged