Nemo launcher dockerfile
aws-samples/awsome-distributed-training pull request #18
Opened 2023-10-12 07:47 UTC by verdimrc

*Issue #, if available:* N/A

*Description of changes:* nemo-launcher: updated the way to build container image for AWS.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-10-16 15:37 UTC, perifaws reviewed
A few commented things to remove

2023-10-16 15:37 UTC, perifaws commented on 3.test_cases/2.nemo-launcher/0.NemoMegatron-aws-optimized.Dockerfile
> +#ENV FI_PROVIDER=efa \
remove as well?

2023-10-16 15:38 UTC, perifaws requested changes

2023-10-16 15:38 UTC, perifaws commented on 3.test_cases/2.nemo-launcher/0.NemoMegatron-aws-optimized.Dockerfile
> +#ENV NCCL_VERSION=inc_nsteps
Remove if commented?

2023-10-17 01:49 UTC, perifaws requested changes

2023-10-17 01:49 UTC, perifaws commented on 3.test_cases/2.nemo-launcher/0.NemoMegatron-aws-optimized.Dockerfile
> +ENV DEBIAN_FRONTEND=noninteractive
good catch

2023-10-17 01:49 UTC, perifaws commented on 3.test_cases/2.nemo-launcher/0.NemoMegatron-aws-optimized.Dockerfile
> +    DEBIAN_FRONTEND=noninteractive apt autoremove -y
shall we keep `DEBIAN_FRONTEND=noninteractive` on the `apt-get` commands? Seems redundant with the `ENV` line 9.

2023-10-26 08:38 UTC, verdimrc commented on 3.test_cases/2.nemo-launcher/0.NemoMegatron-aws-optimized.Dockerfile
> +#ENV FI_PROVIDER=efa \
to validate which paths still need to set minimally.

2023-10-26 16:07 UTC, sean-smith commented on 3.test_cases/2.nemo-launcher/0.NemoMegatron-aws-optimized.Dockerfile
> +# TODO: validate this, based on https://github.com/NVIDIA/NeMo-Megatron-Launcher/blob/7e482f60e00f266a75b9a6964da2afdd2ebe665d/csp_tools/aws/Dockerfile
remove please

2023-10-26 16:07 UTC, sean-smith commented on 3.test_cases/2.nemo-launcher/0.NemoMegatron-aws-optimized.Dockerfile
> +RUN git clone https://github.com/NVIDIA/nccl-tests.git /opt/nccl-tests \
Do we need the nccl tests?

2023-10-27 08:09 UTC, verdimrc commented on 3.test_cases/2.nemo-launcher/0.NemoMegatron-aws-optimized.Dockerfile
> +# TODO: validate this, based on https://github.com/NVIDIA/NeMo-Megatron-Launcher/blob/7e482f60e00f266a75b9a6964da2afdd2ebe665d/csp_tools/aws/Dockerfile
ack, it'll be removed, or minimized, after testing to confirm which additional path + ldpath still needed.

2023-10-27 08:11 UTC, verdimrc commented on 3.test_cases/2.nemo-launcher/0.NemoMegatron-aws-optimized.Dockerfile
> +RUN git clone https://github.com/NVIDIA/nccl-tests.git /opt/nccl-tests \
to me, it's a best practice to include nccl-test as the first-line diagnostic tool to validate container correctness.

2023-11-13 16:10 UTC, perifaws commented
Is the PR still current?

2023-11-13 22:29 UTC, verdimrc commented
yes, it's based on the GA version of nemo container.

2023-11-22 13:00 UTC, verdimrc commented on 3.test_cases/2.nemo-launcher/0.NemoMegatron-aws-optimized.Dockerfile
> +#ENV FI_PROVIDER=efa \
yep, not needed. Base image already takes care of this.

2023-11-22 13:02 UTC, verdimrc commented on 3.test_cases/2.nemo-launcher/0.NemoMegatron-aws-optimized.Dockerfile
> +# TODO: validate this, based on https://github.com/NVIDIA/NeMo-Megatron-Launcher/blob/7e482f60e00f266a75b9a6964da2afdd2ebe665d/csp_tools/aws/Dockerfile
Removed, parent image already takes care of these.

2023-11-22 13:15 UTC, verdimrc commented
@perifaws, @sean-smith: ready for review. All changes tested to work.

2023-11-22 14:42 UTC, perifaws commented
Let's squash the commits, it's only a few changes and 11 commits. Good to go otherwise.

2023-12-05 19:41 UTC, perifaws approved these changes

2023-12-05 19:44 UTC, merged