SMHP: slurm exporter to report gpu metrics
aws-samples/awsome-distributed-training pull request #181
Opened 2024-03-06 07:08 UTC by verdimrc

*Issue #, if available:* N/A

*Description of changes:* Prometheus Slurm exporter to report GPU metrics (total, allocated).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-03-06 15:45 UTC, sean-smith commented
Nice!

2024-03-06 22:03 UTC, perifaws requested changes

2024-03-06 22:03 UTC, perifaws commented on 1.architectures/5.sagemaker-hyperpod/LifecycleScripts/base-config/utils/install_slurm_exporter.sh
> +    git clone -b development https://github.com/vpenso/prometheus-slurm-exporter.git
Set a tag, not dev

2024-03-07 12:25 UTC, verdimrc commented on 1.architectures/5.sagemaker-hyperpod/LifecycleScripts/base-config/utils/install_slurm_exporter.sh
> +    git clone -b development https://github.com/vpenso/prometheus-slurm-exporter.git
`-gpus-acct` throws error with v0.20, contrary to documentation (>=0.19). A few issues link this to Slurm version. The `development` branch works and I can pin to specific commit. 

If `development` branch (pin or not) is not preferred, need to test if `main` branch works. Otherwise, it's either no `-gpus-acct` or pin to the head of `development` branch (latest commit was two years ago anyway).

2024-03-07 17:11 UTC, sean-smith commented on 1.architectures/5.sagemaker-hyperpod/LifecycleScripts/base-config/utils/install_slurm_exporter.sh
> +    git clone -b development https://github.com/vpenso/prometheus-slurm-exporter.git
Can you raise an issue on https://github.com/vpenso/prometheus-slurm-exporter to get another release cut?

2025-05-22 19:19 UTC, closed without merging