DCGM exporter Updates -
aws-samples/awsome-distributed-training pull request #227
Opened 2024-03-28 20:23 UTC by nghtm

- new dcgm_install script to create a systemd service file that will launch the docker container after a node reboot. Also add custom CSV to expand dcgm metrics exported from container to include ECC, Thermal Violations, single-bit, double-bit ECC Errors

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-03-28 20:59 UTC, mhuguesaws approved these changes
Left comments.
No big blockers.

2024-03-28 20:59 UTC, mhuguesaws commented on 1.architectures/5.sagemaker-hyperpod/LifecycleScripts/base-config/utils/install_dcgm_exporter.sh
> +    chmod +x /opt/dcgm-exporter/dcgm-golden-metrics.csv
Why executable on a csv?

2024-03-28 20:59 UTC, mhuguesaws commented on 1.architectures/5.sagemaker-hyperpod/LifecycleScripts/base-config/utils/install_dcgm_exporter.sh
> +       -v /opt/dcgm-exporter:/etc/dcgm-exporter \
You can do the volume only for the file.

2024-03-28 20:59 UTC, mhuguesaws commented on 1.architectures/5.sagemaker-hyperpod/LifecycleScripts/base-config/utils/install_dcgm_exporter.sh
> +    sudo systemctl enable --now dcgm-exporter.service
Indent?

2024-03-29 16:05 UTC, nghtm commented on 1.architectures/5.sagemaker-hyperpod/LifecycleScripts/base-config/utils/install_dcgm_exporter.sh
> +    sudo systemctl enable --now dcgm-exporter.service
Indent is intentional, because lines 151 and 152 are still part of the if statement from line 1 `if nvidia-smi; then` . Line 154 contains the else statement.

2024-03-29 16:26 UTC, nghtm commented on 1.architectures/5.sagemaker-hyperpod/LifecycleScripts/base-config/utils/install_dcgm_exporter.sh
> +       -v /opt/dcgm-exporter:/etc/dcgm-exporter \
Thanks - tested the following successfully, will change and update the PR:
```
    sudo docker run -d --rm \
       --gpus all \
       --net host \
       --cap-add SYS_ADMIN \
       -v /opt/dcgm-exporter/dcgm-golden-metrics.csv:/etc/dcgm-exporter/dcgm-golden-metrics.csv \
       nvcr.io/nvidia/k8s/dcgm-exporter:\${DCGM_EXPORTER_VERSION} \
       -f /etc/dcgm-exporter/dcgm-golden-metrics.csv || { echo "Failed to run DCGM Exporter Docker container"; exit 1; }
```

2024-03-29 16:28 UTC, nghtm commented on 1.architectures/5.sagemaker-hyperpod/LifecycleScripts/base-config/utils/install_dcgm_exporter.sh
> +    chmod +x /opt/dcgm-exporter/dcgm-golden-metrics.csv
Thanks, line 101 is not needed. Will remove in updated PR

2024-04-01 01:47 UTC, sean-smith commented
Please rebase off `origin/main` before merging. i.e.

```
git fetch origin
git rebase origin/main
```

2024-04-01 14:32 UTC, mhuguesaws requested changes
Please rebase

2024-04-02 17:03 UTC, mhuguesaws approved these changes
LGTM

2024-04-02 17:03 UTC, merged