Nemo on eks
aws-samples/awsome-distributed-training pull request #250
Opened 2024-04-08 22:49 UTC by awsankur

This PR has scripts for running NeMo Launcher on EKS. This is in support of a blog we are writing with Nvidia.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-04-08 22:55 UTC, Perif commented
OSX files to be removed. `.DD_Store` ones.

2024-04-08 23:34 UTC, sean-smith commented on 3.test_cases/2.nemo-launcher/EKS/README.md
> +root@cb9511473ccc:/eks# k get pv
Change the following:
```
root@cb9511473ccc:/eks# k get pv
```

to 

```
# kubectl get pv
```

2024-04-08 23:34 UTC, sean-smith commented on 3.test_cases/2.nemo-launcher/EKS/README.md
> +root@cb9511473ccc:/eks/deployment/efa-device-plugin# k get pods -A
use `kubectl get pods -A` instead of `k`

2024-04-08 23:34 UTC, sean-smith commented on 3.test_cases/2.nemo-launcher/EKS/README.md
> +
remove newline

2024-04-08 23:34 UTC, sean-smith commented on 3.test_cases/2.nemo-launcher/EKS/README.md
> +
remove

2024-04-08 23:34 UTC, sean-smith commented on 3.test_cases/2.nemo-launcher/EKS/README.md
> +
remove

2024-04-08 23:34 UTC, sean-smith commented on 3.test_cases/2.nemo-launcher/EKS/README.md
> +Note, in a Slurm cluster implementation the launcher scripts, data and results folder could reside in the filesystem that both the head node (node from where jobs are submitted) and compute nodes. Bu
change to 

> [!TIP]
> Optional information to help a user be more successful.


See https://github.com/orgs/community/discussions/16925

2024-04-08 23:34 UTC, sean-smith commented on 3.test_cases/2.nemo-launcher/EKS/README.md
> +
add description

2024-04-08 23:34 UTC, sean-smith commented on 3.test_cases/2.nemo-launcher/EKS/README.md
> +
remove

2024-04-08 23:34 UTC, sean-smith commented on 3.test_cases/2.nemo-launcher/EKS/launcher_scripts/.DS_Store
remove

2024-04-08 23:34 UTC, sean-smith commented on 3.test_cases/2.nemo-launcher/EKS/launcher_scripts/conf/.DS_Store
remove

2024-04-08 23:34 UTC, sean-smith commented on 3.test_cases/2.nemo-launcher/EKS/launcher_scripts/conf/data_preparation/.DS_Store
remove

2024-04-09 22:17 UTC, KeitaW requested changes

2024-04-09 22:17 UTC, KeitaW commented on 4.validation_and_observability/5.nsight/slurm-esm1nv-train-102.out
We may want to remove the file (as it is too big to render) and put relevant component on the README.

2024-04-09 22:20 UTC, KeitaW commented on 4.validation_and_observability/5.nsight/README.md
> +1. A slurm or Kubernetes cluster is created
Not sure if the current example covers k8s.

2024-04-11 17:03 UTC, mhuguesaws commented on 3.test_cases/2.nemo-launcher/EKS/0.Dockerfile
> +ENV NCCL_VERSION=2.19.4-1
@sean-smith 2.21.5 NCCL is too new and we should recommend NCCL 2.20.3 for now.

2024-04-11 22:38 UTC, mhuguesaws commented on 3.test_cases/2.nemo-launcher/EKS/0.Dockerfile
> +ENV NCCL_TESTS_VERSION=master
pin a version. 2.13.9

2024-04-23 16:31 UTC, awsankur commented on 4.validation_and_observability/5.nsight/README.md
> +1. A slurm or Kubernetes cluster is created
Nsight will be a separate PR. Included by mistake in this PR

2024-04-23 23:15 UTC, KeitaW approved these changes
LGTM, Thanks Ankur for addressing comments!

2024-04-25 22:41 UTC, merged