[Draft, not ready for review] Add llama3 example
aws-samples/awsome-distributed-training pull request #276
Opened 2024-04-19 01:54 UTC by KeitaW

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-05-19 19:24 UTC, pbelevich requested changes
I need to escape $ with \$ when you do `cat > .env ...` otherwise $XYZ values will be evaluated when you run cat and will be empty in the result .env file

2024-05-19 19:24 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/README.md
> +export ENROOT_IMAGE=$APPS_PATH/llama3.sqsh
```suggestion
export ENROOT_IMAGE=\$APPS_PATH/llama3.sqsh
```

2024-05-19 19:24 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/README.md
> +export MODEL_PATH=$FSX_PATH/llama3
```suggestion
export MODEL_PATH=\$FSX_PATH/llama3
```

2024-05-19 19:24 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/README.md
> +export TEST_CASE_PATH=${FSX_PATH}/awsome-distributed-training/3.test_cases/19.llama-recipes
```suggestion
export TEST_CASE_PATH=\${FSX_PATH}/awsome-distributed-training/3.test_cases/19.llama-recipes
```

2024-05-19 19:24 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/README.md
> +export HF_HOME=${FSX_PATH}/.cache
```suggestion
export HF_HOME=\${FSX_PATH}/.cache
```

2024-05-19 19:24 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/README.md
> +export WANDB_CONFIG_DIR=${FSX_PATH}
```suggestion
export WANDB_CONFIG_DIR=\${FSX_PATH}
```

2024-05-19 19:24 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/scripts/generate_env_vars.sh
> +export MODEL_PATH=$FSX_PATH/llama3
```suggestion
export MODEL_PATH=\$FSX_PATH/llama3
```

2024-05-19 19:24 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/scripts/generate_env_vars.sh
> +export ENROOT_IMAGE=$APPS_PATH/llama3.sqsh
```suggestion
export ENROOT_IMAGE=\$APPS_PATH/llama3.sqsh
```

2024-05-19 19:24 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/scripts/generate_env_vars.sh
> +export DATA_PATH=$FSX_PATH/data
```suggestion
export DATA_PATH=\$FSX_PATH/data
```

2024-05-19 19:24 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/scripts/generate_env_vars.sh
> +export TEST_CASE_PATH=${FSX_PATH}/awsome-distributed-training/3.test_cases/19.llama-recipes
```suggestion
export TEST_CASE_PATH=\${FSX_PATH}/awsome-distributed-training/3.test_cases/19.llama-recipes
```

2024-05-19 19:24 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/scripts/generate_env_vars.sh
> +export HF_HOME=${FSX_PATH}/.cache
```suggestion
export HF_HOME=\${FSX_PATH}/.cache
```

2024-05-19 19:24 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/scripts/generate_env_vars.sh
> +export WANDB_CONFIG_DIR=${FSX_PATH}
```suggestion
export WANDB_CONFIG_DIR=\${FSX_PATH}
```

2024-05-19 19:32 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/README.md
> +git clone https://github.com/aws-samples/awsome-distributed-training ${FSX_PATH}
Please mention that $FSX_PATH must be an empty or newly created dir before this step

2024-05-19 19:46 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/README.md
> +You can build the image on your login node using the option 1 below, but build step may exceed the storage available on the head node so we reccomend building it on a compute node following instructi
where is option 2?

2024-05-20 01:32 UTC, pbelevich requested changes

2024-05-20 01:32 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/README.md
> +    enroot start --env NVIDIA_VISIBLE_DEVICES=void \
Probably you missed:
```bash
mkdir -p ${APPS_PATH}
enroot import -o ${ENROOT_IMAGE}  dockerd://llama3:latest
```

2024-05-20 01:32 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/README.md
> +    enroot start --env NVIDIA_VISIBLE_DEVICES=void \
Also, `enroot start` failed for me with `[ERROR] Command not found: squashfuse` on multiple clusters

2024-05-20 01:32 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/README.md
> +    enroot start --env NVIDIA_VISIBLE_DEVICES=void \
And `[ERROR] Command not found: fuse-overlayfs`

2024-05-20 01:32 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/README.md
> +    enroot start --env NVIDIA_VISIBLE_DEVICES=void \
Fixed after `sudo apt-get install squashfuse fuse-overlayfs`

2024-05-20 01:44 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/README.md
> +    enroot start --env NVIDIA_VISIBLE_DEVICES=void \
Maybe HF login can be done without `enroot start`?

2024-05-20 01:48 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/README.md
> +curl https://raw.githubusercontent.com/tatsu-lab/stanford_alpaca/main/alpaca_data.json
curl without args prints the content to the console, probably we need to store it somewhere instead?

2024-05-20 02:46 UTC, pbelevich commented on 3.test_cases/19.llama-recipes/README.md
> +$ ls /fsx/models/meta-llama/Meta-Llama-3-8B-tuned/fine-tuned-meta-llama/Meta-Llama-3-8B/
Sorry, I missed the point how and when was it created, I mean `/fsx/models...`

2024-05-20 12:22 UTC, KeitaW commented on 3.test_cases/19.llama-recipes/README.md
> +curl https://raw.githubusercontent.com/tatsu-lab/stanford_alpaca/main/alpaca_data.json
Yes I was missing `-O alpaca_data.json`

2024-05-20 12:24 UTC, KeitaW commented on 3.test_cases/19.llama-recipes/README.md
> +    enroot start --env NVIDIA_VISIBLE_DEVICES=void \
You can but that requires you to setup Python env with HF locally. Since we have everything in container, I prefer this way. But I agree it's not easy to follow, so packaged it as script in [here](https://github.com/aws-samples/awsome-distributed-training/blob/b6eb957a3de449e5a903dabbb72dbcc51820b407/3.test_cases/torchtitan-torchtune/slurm/2.download_hf_model.sh) .

2024-05-20 12:27 UTC, KeitaW commented on 3.test_cases/19.llama-recipes/README.md
> +    enroot start --env NVIDIA_VISIBLE_DEVICES=void \
https://github.com/aws-samples/awsome-distributed-training/blob/b6eb957a3de449e5a903dabbb72dbcc51820b407/1.architectures/2.aws-parallelcluster/distributed-training-p4de_postinstall_scripts.yaml

2024-05-20 12:28 UTC, closed without merging