Add LDAP Server
aws-samples/awsome-distributed-training pull request #311
Opened 2024-05-06 17:59 UTC by mhuguesaws

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-05-06 20:31 UTC, sean-smith commented on 1.architectures/6.ldap_server/cf_ldap_server.yaml
> +  LdapKeyPair:
Does the user need this to access to the LDAP instance?

2024-05-06 20:31 UTC, sean-smith commented on 1.architectures/6.ldap_server/cf_ldap_server.yaml
> +    NoEcho: true
Can this be avoided by using Secrets Manager?

2024-05-06 21:28 UTC, mhuguesaws commented on 1.architectures/6.ldap_server/cf_ldap_server.yaml
> +  LdapKeyPair:
A User won't need access.
An admin will want to access the instance for various reasons: maintenance, upgrades etc...

2024-05-06 21:29 UTC, mhuguesaws commented on 1.architectures/6.ldap_server/cf_ldap_server.yaml
> +    NoEcho: true
We can use secret manager to generate a secure string. It won't handle password rotation.

2024-05-07 17:53 UTC, nghtm approved these changes
Looks good - adding a ReadMe is my only feedback. 

Tested the template in my isengard account, deployed successfully in a public subnet, but do not know what to do next without any setup instructions

2024-05-07 17:54 UTC, mhuguesaws commented
Let me add some documentation before merging. Forgot about that.

2024-05-07 18:13 UTC, sean-smith commented
> Looks good - adding a ReadMe is my only feedback.
> 
> Tested the template in my isengard account, deployed successfully in a public subnet, but do not know what to do next without any setup instructions

I think we should include the setup instructions for both PC and SMHP as a separate PR.

2024-05-07 19:54 UTC, perifaws requested changes

2024-05-07 19:54 UTC, perifaws commented on 1.architectures/6.ldap_server/cf_ldap_server.yaml
> +    Description: 'Ubuntu 22.04 AMI Id'
`Id` -> `ID`

2024-05-07 19:54 UTC, perifaws commented on 1.architectures/6.ldap_server/cf_ldap_server.yaml
> +
remove extra line

2024-05-07 19:54 UTC, perifaws commented on 1.architectures/6.ldap_server/cf_ldap_server.yaml
> +
remove extra line

2024-05-14 18:01 UTC, sean-smith commented
What's needed here?

2024-05-14 18:04 UTC, mhuguesaws commented
more documentation. It is coming.

2024-05-14 22:19 UTC, mhuguesaws commented
@sean-smith minimal doc completed. Ready for your review.

2024-05-14 22:43 UTC, sean-smith approved these changes

2024-05-16 15:40 UTC, perifaws approved these changes

2024-05-16 15:41 UTC, merged