[Draft] Multi-node Stable Diffusion
aws-samples/awsome-distributed-training pull request #33
Opened 2023-11-02 16:58 UTC by sean-smith

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-11-14 19:26 UTC, perifaws requested changes

2023-11-14 19:26 UTC, perifaws commented on 3.test_cases/6.stable-diffusion/multi-node/1.Dockerfile
> +RUN sed -i 's/[ #]\(.*StrictHostKeyChecking \).*/ \1no/g' /etc/ssh/ssh_config && \
required?

2023-11-14 19:26 UTC, perifaws commented on 3.test_cases/6.stable-diffusion/multi-node/1.Dockerfile
> + && python3 /tmp/get-pip.py \
indentation is not consistent

2023-11-14 19:26 UTC, perifaws commented on 3.test_cases/6.stable-diffusion/multi-node/1.Dockerfile
> +RUN pip3 install mosaicml==0.15.0 --force
version as an env var?

2023-11-14 19:26 UTC, perifaws commented on 3.test_cases/6.stable-diffusion/multi-node/2.train.sbatch
> +        benchmark.py \
where is this file?

2023-11-15 20:24 UTC, awsankur commented on 3.test_cases/6.stable-diffusion/multi-node/1.Dockerfile
> +RUN sed -i 's/[ #]\(.*StrictHostKeyChecking \).*/ \1no/g' /etc/ssh/ssh_config && \
These lines are not specific to the stable diffusion model. Taken from the Dockerfile for NCCL tests:
https://github.com/aws-samples/awsome-distributed-training/blob/multi-node/4.validation_scripts/0.nccl-tests/0.nccl-tests.Dockerfile

2023-11-15 20:32 UTC, awsankur commented on 3.test_cases/6.stable-diffusion/multi-node/1.Dockerfile
> +RUN pip3 install mosaicml==0.15.0 --force
Added new env variable

2023-11-15 20:37 UTC, awsankur commented on 3.test_cases/6.stable-diffusion/multi-node/2.train.sbatch
> +        benchmark.py \
The multi-node Dockerfile is cloning the MosaicML stable diffusion benchmark repo and `benchmark.py` lies in the WORKDIR `/workspace/diffusion-benchmark`

2023-11-15 20:40 UTC, awsankur commented on 3.test_cases/6.stable-diffusion/multi-node/2.train.sbatch
> +NODE_RANK=1
Yes, MosaicML's stable diffusion is a pretty popular implementation. This workaround to get MosaicML's Composer working with Slurm might benefit from a review by MosaicML.

2023-11-15 20:41 UTC, awsankur commented on 3.test_cases/6.stable-diffusion/multi-node/1.Dockerfile
> +ENV LD_PRELOAD /opt/nccl/build/lib/libnccl.so
Not 100% sure. Probably safe to keep it.

2023-11-16 22:41 UTC, perifaws commented on 3.test_cases/6.stable-diffusion/single-node/0.Dockerfile
> +ARG MOSAICML_VERSION
Use default values

2023-11-16 22:41 UTC, perifaws commented on 3.test_cases/6.stable-diffusion/README.md
>  Make sure you are able to create conda environments and docker containers. For example, to install Miniconda, please follow the steps below:
You may want to clarify why one need Conda while we are using containers

2023-11-16 22:41 UTC, perifaws commented on 3.test_cases/6.stable-diffusion/README.md
>  The `single-node` folder also has the Dockerfile and a Makefile with commands to build the image and run the container.
Are there thing to know about his container? What does it do?

2023-11-16 22:41 UTC, perifaws commented on 3.test_cases/6.stable-diffusion/README.md
>  ### 1.2 Single Node Training
Same title as the section?

2023-11-16 22:41 UTC, perifaws commented on 3.test_cases/6.stable-diffusion/README.md
> +The older `self.unet.set_attn_processor(AttnProcessor())` gives Cuda OOM error with a batch size of 32 while with `AttnProcessor2_0()` is able to run with a batch size of 32 and yield 385 images/sec
Could we reference to a CUDA OOM? (just a link)

2023-11-16 22:41 UTC, perifaws commented on 3.test_cases/6.stable-diffusion/README.md
> +For the multi-node training we've created a `Dockerfile`, and Slurm submit script and a `Makefile` to build the docker image and convert it to an enroot image. To get started please follow the guide
remove the makefile reference

2023-11-16 22:43 UTC, perifaws commented on 3.test_cases/6.stable-diffusion/README.md
> +Next build the docker image:
no more numbered list?

2023-11-18 07:28 UTC, awsankur commented on 3.test_cases/6.stable-diffusion/README.md
>  Make sure you are able to create conda environments and docker containers. For example, to install Miniconda, please follow the steps below:
Added clarification

2023-11-19 07:19 UTC, KeitaW reviewed
Left some minor comments. Kudos @sean-smith  and @awsankur  for this great work!

2023-11-19 07:19 UTC, KeitaW commented on 3.test_cases/6.stable-diffusion/README.md
> +export MINICONDA_INSTALLER=Miniconda3-py310_23.5.2-0-Linux-x86_64
If `miniconda` example is deprecated, this variable can be removed too.

2023-11-19 07:19 UTC, KeitaW commented on 3.test_cases/6.stable-diffusion/README.md
>  When testing the latest version of MosaicML's Composer, we found that different ways to set up the environment with a PyTorch Nightly conda environment or a Nvidia PyTorch Docker container. For singl
This sentence is also need to be revised.

2023-11-19 07:19 UTC, KeitaW commented on 3.test_cases/6.stable-diffusion/multi-node/2.train.sbatch
> +: "${IMAGE:=$APPS_PATH/mosaicml/stable-diffusion.sqsh}"
According to the  `README.md` the sqsh file supposed to be stored as `$APPS_PATH/mosaicml-stable-diffusion.sqsh `.

2023-11-19 07:19 UTC, KeitaW commented on 3.test_cases/6.stable-diffusion/multi-node/2.train.sbatch
> +: "${APPS_PATH:=/fsx}"
In `RERADME.md`, `APPS_PATH` is implicitly specified as `/apps`. Better to follow to the default value here.

2023-11-19 07:19 UTC, KeitaW commented on 3.test_cases/6.stable-diffusion/single-node/0.Dockerfile
>  RUN pip3 uninstall transformer-engine -y
I am not sure if the current example making use of transformer-engine. It seems that the original repo isn't integrate the feature yet?

2023-11-19 07:23 UTC, KeitaW commented
[This is a general comment. No need to address in this PR.] I believe that the only difference between the docker image of `single-node` and `multi-node` is EFA/NCCL related settings. We may use multi-stage build feature to unify those two.

2023-11-19 07:30 UTC, KeitaW commented
Hmm... actually my multi-node job failed with the following error on P5 cluster.
```
0: p5-st-p5-2:947575:949672 [0] NCCL INFO proxy.cc:858 -> 2 [Proxy Thread]
0: wandb: Tracking run with wandb version 0.13.11
0: wandb: W&B syncing is set to `offline` in this directory.  
0: wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
0: wandb: WARNING URL not available in offline run
0: p5-st-p5-1:1130982:1133081 [0] NCCL INFO [Service thread] Connection closed by localRank 4
0: p5-st-p5-1:1130982:1133081 [0] NCCL INFO [Service thread] Connection closed by localRank 2
0: p5-st-p5-1:1130982:1133081 [0] NCCL INFO [Service thread] Connection closed by localRank 3
```
any thoughts on the root cause? I'm working with 
* pclustre 3.7.2
* AMI: Base DLAMI 10/26

2023-11-19 08:10 UTC, KeitaW commented
Hmm... although the job is up and running, I don't see any meaningful output. Any thoughts on the cause? I'm using 
* Pcluster 3.7.2
* AMI: Base DLAMI 10/16

```
$ squeue
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
               277        p5 mosaicml   ubuntu  R      53:51      2 p5-st-p5-[1-2]

$ tail -f jobs/slurm-277.out 
0: p5-st-p5-2:947575:949672 [0] NCCL INFO transport/net.cc:1112 -> 2
0: p5-st-p5-2:947575:949672 [0] NCCL INFO proxy.cc:679 -> 2
0: p5-st-p5-2:947575:949672 [0] NCCL INFO proxy.cc:858 -> 2 [Proxy Thread]
0: wandb: Tracking run with wandb version 0.13.11
0: wandb: W&B syncing is set to `offline` in this directory.  
0: wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
0: wandb: WARNING URL not available in offline run
0: p5-st-p5-1:1130982:1133081 [0] NCCL INFO [Service thread] Connection closed by localRank 4
0: p5-st-p5-1:1130982:1133081 [0] NCCL INFO [Service thread] Connection closed by localRank 2
0: p5-st-p5-1:1130982:1133081 [0] NCCL INFO [Service thread] Connection closed by localRank 3
```

2023-11-29 14:35 UTC, awsankur commented on 3.test_cases/6.stable-diffusion/README.md
>  When testing the latest version of MosaicML's Composer, we found that different ways to set up the environment with a PyTorch Nightly conda environment or a Nvidia PyTorch Docker container. For singl
For Single Node Section 1.2 shows setup with a Conda environment and 1.3 an optional step with Docker.

2023-11-29 14:38 UTC, awsankur commented on 3.test_cases/6.stable-diffusion/single-node/0.Dockerfile
>  RUN pip3 uninstall transformer-engine -y
Yes

2023-11-29 14:40 UTC, awsankur commented
> Hmm... although the job is up and running, I don't see any meaningful output. Any thoughts on the cause? I'm using
> 
> * Pcluster 3.7.2
> * AMI: Base DLAMI 10/16
> 
> ```
> $ squeue
>              JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
>                277        p5 mosaicml   ubuntu  R      53:51      2 p5-st-p5-[1-2]
> 
> $ tail -f jobs/slurm-277.out 
> 0: p5-st-p5-2:947575:949672 [0] NCCL INFO transport/net.cc:1112 -> 2
> 0: p5-st-p5-2:947575:949672 [0] NCCL INFO proxy.cc:679 -> 2
> 0: p5-st-p5-2:947575:949672 [0] NCCL INFO proxy.cc:858 -> 2 [Proxy Thread]
> 0: wandb: Tracking run with wandb version 0.13.11
> 0: wandb: W&B syncing is set to `offline` in this directory.  
> 0: wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
> 0: wandb: WARNING URL not available in offline run
> 0: p5-st-p5-1:1130982:1133081 [0] NCCL INFO [Service thread] Connection closed by localRank 4
> 0: p5-st-p5-1:1130982:1133081 [0] NCCL INFO [Service thread] Connection closed by localRank 2
> 0: p5-st-p5-1:1130982:1133081 [0] NCCL INFO [Service thread] Connection closed by localRank 3
> ```

I have made changes to the Dockerfile to make sure this issue does not happen and training proceeds successfully.

2023-11-29 14:42 UTC, merged