Trainium llama3
aws-samples/awsome-distributed-training pull request #363
Opened 2024-06-22 10:24 UTC by syedazi

*Description of changes:*
This is an example for running Llama 3 8B and 70B model on SageMaker Hyperpod using Trainium instances.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-06-24 15:57 UTC, nghtm reviewed
This is an initial review of just the readme, not the code. 

I have requested access to the llama3 model in Huggingface and will complete a full review once I have been granted access and complete the training portition.

2024-06-24 15:57 UTC, nghtm commented on 3.test_cases/22.SMHP-trainium-llama3/README.md
> +Once you have downloaded the tokenizer and model weights, you can copy the tokenizer.model, config.json and tokenizer.json files from the Llama 3 repo to the working directory (22.SMHP-trainium-llama
put the directory 22.SMHP-trainium-llama3 in markdown `22.SMHP-trainium-llama3`

2024-06-24 15:57 UTC, nghtm commented on 3.test_cases/22.SMHP-trainium-llama3/README.md
> +1. Once the cluster is set up, SSH into the cluster and switch to the `ubuntu` user:
Can we specify whether this should be on the controller node or a compute node (trn1 instance)

2024-06-24 15:57 UTC, nghtm commented on 3.test_cases/22.SMHP-trainium-llama3/README.md
> +Next, we need to tokenize our dataset. To tokenize the data, you must request the tokenizer from HuggingFace and Meta by following the instructions at the following link: [HuggingFace Llama 3 8B Mode
I just requested access via Huggingface which is now pending. 

Maybe we include this as a flag in the readme, or a pre-requisites section with the flag 

> [!IMPORTANT]  
To tokenize the data, you must request the tokenizer from HuggingFace and Meta by following the instructions at the following link: [HuggingFace Llama 3 8B Model](https://huggingface.co/meta-llama/Meta-Llama-3-8B) . Use of the Llama 3 model is governed by the Meta license. In order to download the model weights and tokenizer, please visit the above website and accept their License before requesting access. After access has been granted, you may use the download scripts provided by Meta to download the model weights and tokenizer to your cluster.

2024-06-24 15:57 UTC, nghtm commented on 3.test_cases/22.SMHP-trainium-llama3/README.md
> +## 4. Run Training
Lets specify with a comment that by default, this is the 8B model

2024-06-24 17:58 UTC, nghtm commented on 3.test_cases/22.SMHP-trainium-llama3/README.md
> +source aws_neuron_venv_pytorch/bin/activate
Lets break this out as a seperate code block, and ensure with a check that the python venv gets acctivated successfully. When I just copy and paste the script on the head node, it did not correctly source the venv

2024-06-24 17:58 UTC, nghtm commented on 3.test_cases/22.SMHP-trainium-llama3/README.md
> +Once you have downloaded the tokenizer and model weights, you can copy the tokenizer.model, config.json and tokenizer.json files from the Llama 3 repo to the working directory (22.SMHP-trainium-llama
Lets provide instructions to clone the llama3 repo and copy the `tokenizer.model`, `config.json` and `tokenizer.json` files to the working directory.

2024-06-24 17:58 UTC, nghtm commented on 3.test_cases/22.SMHP-trainium-llama3/README.md
> +Once you have downloaded the tokenizer and model weights, you can copy the tokenizer.model, config.json and tokenizer.json files from the Llama 3 repo to the working directory (22.SMHP-trainium-llama
```
pip install huggingface-hub

huggingface-cli login
#authenticate with HuggingFace Access Token (https://huggingface.co/settings/tokens). Ensure your token gives permissions to public gated repos (Edit Acces Token Permissions > Read access to contents of all public gated repos you can access)

pip install huggingface-hub

huggingface-cli login
#authenticate with HuggingFace Access Token (https://huggingface.co/settings/tokens). Ensure your token gives permissions to public gated repos (Edit Acces Token Permissions > Read access to contents of all public gated repos you can access)

huggingface-cli download meta-llama/Meta-Llama-3-8B --local-dir Meta-Llama-3-8B

cp Meta-Llama-3-8B/original/* .
```

2024-06-24 17:58 UTC, nghtm commented on 3.test_cases/22.SMHP-trainium-llama3/README.md
> +Once you have downloaded the tokenizer and model weights, you can copy the tokenizer.model, config.json and tokenizer.json files from the Llama 3 repo to the working directory (22.SMHP-trainium-llama
Question: Should we download the model from Huggingface Hub using the flag `--include "original/*"`?

When I do so, it only contains the contents of [the original directory](https://huggingface.co/meta-llama/Meta-Llama-3-8B/tree/main/original), and not the parent directories, so I am missing the files `tokenizer.json` and `config.json`

2024-06-24 17:58 UTC, nghtm commented on 3.test_cases/22.SMHP-trainium-llama3/README.md
> +python3 get_dataset.py
When I run this command, I get the following error:

```
ubuntu@ip-10-1-28-68:~/awsome-distributed-training/3.test_cases/22.SMHP-trainium-llama3$ python3 get_dataset.py
Traceback (most recent call last):
  File "get_dataset.py", line 1, in <module>
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'
(aws_neuron_venv_pytorch) ubuntu@ip-10-1-28-68:~/awsome-distributed-training/3.test_cases/22.SMHP-trainium-llama3$ ls -a
.                activation_checkpoint.py  get_dataset.py         params.json             run_llama_nxd.py
..               config.json               logger.py              requirements.txt        tokenizer.json
Meta-Llama-3-8B  consolidated.00.pth       lr.py                  run_llama_70B_tp_pp.sh  tokenizer.model
README.md        convert_checkpoints.py    modeling_llama_nxd.py  run_llama_8B_tp_pp.sh   training_utils.py
```

2024-06-24 17:58 UTC, nghtm commented on 3.test_cases/22.SMHP-trainium-llama3/README.md
> +python3 get_dataset.py
To fix this, I need to run:

```
pip install -r requirements.txt
```

2024-06-24 17:58 UTC, nghtm commented on 3.test_cases/22.SMHP-trainium-llama3/README.md
> +python3 get_dataset.py
^lets add this step to the creation of the **1. Create Environment** section

2024-06-24 17:58 UTC, nghtm commented on 3.test_cases/22.SMHP-trainium-llama3/README.md
> +python3 get_dataset.py
Also seeing this error when trying to execute `get_dataset.py`:

```
RecursionError: maximum recursion depth exceeded while calling a Python object
```

2024-06-24 18:42 UTC, nghtm commented on 3.test_cases/22.SMHP-trainium-llama3/README.md
> +python3 get_dataset.py
I was able to reslove this error by copying `tokenizer_config.json` to local directory

2024-06-24 18:46 UTC, nghtm commented on 3.test_cases/22.SMHP-trainium-llama3/README.md
> +python3 get_dataset.py
Given the current repository structure on HF for Llama3, after cloning, here is the correct command to copy the files into local directory: `22.SMHP-trainium-llama3`:

```
cp /Meta-Llama-3-8B/tokenizer_config.json /Meta-Llama-3-8B/config.json /Meta-Llama-3-8B/tokenizer.json /Meta-Llama-3-8B/original/tokenizer.model .

```

2024-06-24 19:10 UTC, nghtm commented on 3.test_cases/22.SMHP-trainium-llama3/README.md
> +--wrap="srun bash $(pwd)/run_llama_8B_tp_pp.sh"
When running the compile script, I get this error:


```
OSErrorOSError: OSError: : Can't load the configuration of '/fsx/ubuntu/awsome-distributed-training/3.test_cases/22.SMHP-trainium-llama3/8B_config_llama3'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/fsx/ubuntu/awsome-distributed-training/3.test_cases/22.SMHP-trainium-llama3/8B_config_llama3' is the correct path to a directory containing a config.json fileCan't load the configuration of '/fsx/ubuntu/awsome-distributed-training/3.test_cases/22.SMHP-trainium-llama3/8B_config_llama3'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/fsx/ubuntu/awsome-distributed-training/3.test_cases/22.SMHP-trainium-llama3/8B_config_llama3' is the correct path to a directory containing a config.json fileCan't load the configuration of '/fsx/ubuntu/awsome-distributed-training/3.test_cases/22.SMHP-trainium-llama3/8B_config_llama3'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/fsx/ubuntu/awsome-distributed-training/3.test_cases/22.SMHP-trainium-llama3/8B_config_llama3' is the correct path to a directory containing a config.json file
```

2024-06-24 20:08 UTC, nghtm commented on 3.test_cases/22.SMHP-trainium-llama3/README.md
> +--wrap="srun bash $(pwd)/run_llama_8B_tp_pp.sh"
I was able to resolve this error by copying the attached `config.json` file to my working directory within the following subdirectory:

`22.SMHP-trainium-llama3/8B_config_llama3/config.json`

[config.json](https://github.com/user-attachments/files/15960705/config.json)

2024-06-24 21:35 UTC, nghtm approved these changes
Reviewed and updated the ReadMe, added necessary config scripts to the working directory `22.SMHP-trainium-llama3`. I have tested this sample on an 4 node trn1.32xlarge SMHP cluster, successfully trained llama-8B on 4 nodes

2024-06-24 23:03 UTC, KeitaW requested changes
The README looks great and comprehensive. However, I am uncertain if we want to own the NxD codebase. It appears to be largely a copy of the [NxD Llama2 example](https://github.com/aws-neuron/neuronx-distributed/tree/main/examples/training/llama2), with some additional changes expected to come with Neuron SDK 2.19.
Additionally, Neuron SDK team are working on a few more changes to improve performance. Should we consider basing our work on the original codebase and simply prepare the guidance in `README`?

2024-06-25 09:42 UTC, KeitaW commented
### Interim Solution for Llama3 Training
As discussed with @syedazi, we have decided to implement a temporary measure to address our current needs:
* We will incorporate the NxD codebase as an interim solution.
* This arrangement will remain in place until the release of Neuron SDK 2.19.
### Post-Release Actions
Once Neuron SDK 2.19 becomes available:
* The temporary NxD codebase will be removed from our repository.
* We will update the README file to provide comprehensive guidance for users.
    * This update will include instructions on how to train Llama3 using the latest NxD version.

2024-06-25 09:42 UTC, KeitaW approved these changes

2024-06-25 10:03 UTC, merged