implementing slurm.schedmd.com/pam_slurm_adopt.html to add cgroups, pam_slurm_adopt and ssh admin access
aws-samples/awsome-distributed-training pull request #429
Opened 2024-09-13 21:23 UTC by gmgtamz

1. Limit host memory usage at 99% MaxRAMPercent using cgroup enforcement
2. Prevent user to ssh without jobs running on that node using adding pam_slurm_adopt PAM module
3. Since pam_slurm_adopt will block ssh user access, we add a wheel group mechanism to authorize admin users to ssh with 2 different PAM modules.

pam_slurm_adopt will always allow the root user access. To allow other admins to the system, there are 2 PAM implemented options to allow users to ssh:
1. pam_access.so using ${access_conf}
2. pam_listfile.so using ${wheel_list}

pam_slurm_adopt
The purpose of this module is to prevent users from sshing into nodes that they do not have a running job on, and to track the ssh connection and
any other spawned processes for accounting and to ensure complete job cleanup when the job is completed. This module does this by determining the job
which originated the ssh connection. The user's connection is "adopted" into the "external" step of the job.
When access is denied, the user will receive a relevant error message.

This script is doing 3 actions following the documentation from https://slurm.schedmd.com/pam_slurm_adopt.html

2024-09-16 14:45 UTC, perifaws requested changes

2024-09-16 14:45 UTC, perifaws commented on 1.architectures/5.sagemaker-hyperpod/LifecycleScripts/base-config/utils/pam_adopt_cgroup_wheel.sh
> +# The purpose of this module is to prevent users from sshing into nodes that they do not have a running job on, and to track the ssh connection and
This section should be at the top as it explains the purpose of this code.

2024-09-16 16:04 UTC, perifaws commented on 1.architectures/5.sagemaker-hyperpod/LifecycleScripts/base-config/utils/pam_adopt_cgroup_wheel.sh
> +# apt_opts='-o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"'
Copy, either add a comment to say that or remove. It can be confusing on why it is here otherwise. Thanks!

2024-09-16 16:04 UTC, perifaws commented on 1.architectures/5.sagemaker-hyperpod/LifecycleScripts/base-config/utils/pam_adopt_cgroup_wheel.sh
> +    # Access denied by pam_slurm_adopt: you have no active jobs on this node
Ok, good to indicate it's the case then.

2024-09-16 16:04 UTC, perifaws commented on 1.architectures/5.sagemaker-hyperpod/LifecycleScripts/base-config/utils/pam_adopt_cgroup_wheel.sh
> +# The purpose of this module is to prevent users from sshing into nodes that they do not have a running job on, and to track the ssh connection and
Meaning at the very top, it really is the explanation of what this code does.

2024-09-16 18:57 UTC, nghtm commented
Is the latest script ready for testing?

2024-09-18 21:31 UTC, mhuguesaws approved these changes
Thank you for updating the description. Much clearer.
LGTM.

2024-09-18 21:31 UTC, merged