Improvements/#427
aws-samples/awsome-distributed-training pull request #438
Opened 2024-09-20 22:15 UTC by nghtm

*Issue #, if available:* https://github.com/aws-samples/awsome-distributed-training/issues/427

*Description of changes:* This PR has 3 commits, each addressing separate issues.  

* [Commit 92d1b0c](https://github.com/aws-samples/awsome-distributed-training/commit/82d1b0c3e049a5d8afaae1620505b4d68676e8ef) to fix incorrect config param in config.py, previously undocumented issue. 

* [Commit abd677e](https://github.com/aws-samples/awsome-distributed-training/commit/abd677e5044693ca8b1c5b7ee453903fee61a11b) to modify order which Docker / Enroot / Pyxis is called in lifecycle scripts, to mitigate chance of encountering race condition documented in issue 427

* [Commit 3c9a655](https://github.com/aws-samples/awsome-distributed-training/commit/3c9a65582b413771de17c4207983720f9c174a4d) to further address 427 by adding a while loop that will poll (max 120s) dlami-nvme.service for active and execStart messages. This provides assurance that /opt/dlami/nvme is mounted to node prior to executing enroot configuration which will use /opt/dlami/nvme. This commit also updates the order of if/elif statement to first try /opt/dlami/nvme before /opt/sagemaker. 

This PR has been tested successfully on a HyperPod cluster with 1 p5 and 4 c5.4xlarge to verify intended outcome and logs analyzed to confirm while loop functioning properly. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-09-20 23:02 UTC, mhuguesaws commented on 1.architectures/5.sagemaker-hyperpod/LifecycleScripts/base-config/utils/install_enroot_pyxis.sh
> +elif [[ $(mount | grep /opt/sagemaker) ]]; then
This is repeated twice.

2024-09-20 23:03 UTC, mhuguesaws requested changes
need changes.

2024-09-21 00:03 UTC, nghtm commented on 1.architectures/5.sagemaker-hyperpod/LifecycleScripts/base-config/utils/install_enroot_pyxis.sh
> +elif [[ $(mount | grep /opt/sagemaker) ]]; then
thank you, resolved in latest commit

2024-09-21 00:06 UTC, nghtm commented
resolved comment from mhugueaws

2024-09-21 15:25 UTC, mhuguesaws approved these changes
LGTM

2024-09-23 02:34 UTC, merged