revise neuronx-nemo-megatron example
aws-samples/awsome-distributed-training pull request #49
Opened 2023-11-19 03:26 UTC by KeitaW

*Issue #, if available:*

*Description of changes:*

This PR is aiming to address some of the remaining comments @perifaws kindly made on the previous PR (https://github.com/aws-samples/awsome-distributed-training/pull/48).  

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-11-21 14:57 UTC, perifaws requested changes

2023-11-25 18:12 UTC, KeitaW commented on 3.test_cases/8.neuronx-nemo-megatron/2.setup-neuronx-nemo-megatron.sh
> +pip3 install -r requirements.txt torch==1.13.1 protobuf==3.20.3
Actually, the `neuronx-nemo-megatron` is picky for the pytorch version. I would like to hard code the value until it relax the requirement.

2023-11-25 19:05 UTC, KeitaW commented on 3.test_cases/8.neuronx-nemo-megatron/4.tokenize.sbatch
> +#SBATCH --cpus-per-task 96
The value was arbitrary. I fixed them to 128.

2023-11-25 19:05 UTC, KeitaW commented on 3.test_cases/8.neuronx-nemo-megatron/4.tokenize.sbatch
> +    --workers=32
The value was arbitrary. I fixed them to 128.

2023-11-25 20:09 UTC, KeitaW commented on 3.test_cases/8.neuronx-nemo-megatron/README.md
> +wget https://data.together.xyz/redpajama-data-1T/v1.0.0/book/book.jsonl -O ${DATA_PATH}/book.jsonl # Note: Dataset download is 50G and will take approximately 3-4 hours to download.
For quick testing,  we can always use `book_sample.jsonl` instead. I have added guidance for the sample data and faster download with `Aria2` in readme.

2023-11-25 20:29 UTC, KeitaW commented on 3.test_cases/8.neuronx-nemo-megatron/5.precompile-model.sh
> +cd ${APPS_PATH}/neuronx-nemo-megatron/nemo/examples/nlp/language_modeling
True, omitted.

2023-11-25 20:29 UTC, KeitaW commented on 3.test_cases/8.neuronx-nemo-megatron/6.pretrain-model.sh
> +export TEST_CASE_PATH=${APPS_PATH}/awsome-distributed-training/3.test_cases/8.neuronx-nemo-megatron  # where you copy the test case or set to your test case path
True, omitted.

2023-11-25 20:31 UTC, KeitaW commented on 3.test_cases/8.neuronx-nemo-megatron/README.md
> +First of all, you need to have a Python virtual environment for `torch-neuronx` under `APPS_PATH`.
added numbers

2023-11-25 20:35 UTC, KeitaW commented on 3.test_cases/8.neuronx-nemo-megatron/README.md
> +```
Thanks for catching this! updated

2023-11-25 20:37 UTC, KeitaW commented on 3.test_cases/8.neuronx-nemo-megatron/README.md
> +Once job completed, you will have the Llama-2-7b in a huggingface format under a directory called `Llama2-7b-hf` with the following format:
Updated to 

> Once the job completed, you will have the Llama-2-7b model weights and tokenizer in a huggingface format under a directory called `Llama2-7b-hf` with the following format:

2023-11-27 03:06 UTC, perifaws approved these changes

2023-11-27 03:07 UTC, merged

2023-11-27 03:08 UTC, perifaws commented
Merged, congrats and thanks @KeitaW !