SageMaker data parallelism examples on HyperPod
aws-samples/awsome-distributed-training pull request #83
Opened 2023-12-19 16:57 UTC by ruhanprasad

*Issue #, if available:*

*Description of changes:*
Shows how to use SageMaker Data Parallel library on Hyperpod for PyTorch FSDP and DeepSpeed training jobs

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-01-05 11:12 UTC, verdimrc requested changes
Please remove `__pycache__` -- also make sure to remove it from the git history.

2024-01-05 16:58 UTC, perifaws requested changes

2024-01-05 16:58 UTC, perifaws commented on 3.test_cases/12.SM-dataparallel-FSDP/README.md
> +The SMDDP library provides fast GPU collective communication algorithms on P4d/P4de instance types and serves as a drop-in replacement for the Nvidia Collective Communications Library (NCCL).  Specif
You may want to add links to Falcon, FSDP, NCCL and SMDPP in case users want to get more information.

2024-01-05 16:58 UTC, perifaws commented on 3.test_cases/12.SM-dataparallel-FSDP/README.md
> +You will need a slurm cluster with an FSx for Lustre file system.  See the sagemaker-hyperpod section in the [1.architectures](https://github.com/ruhanprasad/awsome-distributed-training/tree/main/1.a
Slurm cluster with a shared parallel file-system, for example Amazon FSx for Lustre <- include link to FSxL doc (not the product landing page).

See the sagemaker-hyperpod section in the ... -> point directly to the section via a relative link. You are using an absolute one!

2024-01-05 16:58 UTC, perifaws commented on 3.test_cases/13.SM-dataparallel-deepspeed/README.md
> +You will need a slurm cluster with an FSx for Lustre file system.  See the sagemaker-hyperpod section in the [1.architectures](https://github.com/ruhanprasad/awsome-distributed-training/tree/main/1.a
Reference to an absolute path, should be relative.

2024-01-09 23:12 UTC, perifaws commented on 3.test_cases/12.SM-dataparallel-FSDP/scripts/requirements.txt
> +datasets
You may want to set the versions here. It'll ensure some reproducibility.

2024-01-12 02:22 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/README.md
> +You will need a slurm cluster with a shared parallel filesystem such as [Amazon FSx for Lustre](https://docs.aws.amazon.com/fsx/latest/LustreGuide/getting-started.html).  See the sagemaker-hyperpod s
Slurm (capitalized s).

2024-01-12 02:23 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/README.md
> +You will need a slurm cluster with a shared parallel filesystem such as [Amazon FSx for Lustre](https://docs.aws.amazon.com/fsx/latest/LustreGuide/getting-started.html).  See the sagemaker-hyperpod s
> See the sagemaker-hyperpod section in the [1.architectures/5.sagemaker-hyperpod](https://github.com/aws-samples/awsome-distributed-training/tree/main/1.architectures/5.sagemaker-hyperpod) folder for setup instructions. 

Which section in the readme?

2024-01-12 02:26 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/README.md
> +The [SMDDP](https://docs.aws.amazon.com/sagemaker/latest/dg/data-parallel.html) library provides fast GPU collective communication algorithms on P4d/P4de instance types and serves as a drop-in replac
Nits:
* link to p4d or p4de pages.
* this is first time this doc mentions instance types, so consider to use full form p4d.24xlarge and p4de.24xlarge

2024-01-12 02:26 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/README.md
> +Additionally, SMDDP must be used on AWS P4d or P4de instances.  This example also uses mamba as a package manager.  Mamba is a drop-in replacement for conda and it is recommended over Miniconda or An
Nits:

* `mamba` or `conda` when referring to CLI.
* Links to first mention of Mamba, {Mini,Ana}conda.

2024-01-12 02:29 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/README.md
> +2. Clone this repo
Combine 1/ and 2/ into: "On your cluster head node, clone this repo to the shared FSx filesystem `/fsx`." No numbering needed.

2024-01-12 02:30 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/README.md
> +Launching the job will create a log file in the current directory (`slurm-<job_id>`)  which you can tail to monitor the progress of the training job.    You can also see the underlying launch script
> which you can tail to monitor

Would be nice to show example, esp. if this is `tail -f ...`.

2024-01-12 02:35 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/README.md
> +If this occurs, firstly ensure that you are installing PyTorch via conda before pip installing SMDDP (i.e. install PyTorch through `conda install` before installing SMDDP in your environment).  If th
This reads like known issue when not following the installation procedure earlier in this doc? If so, suggest to flip the order of paragraph: start by reminding users to follow those steps, then you could talk about why the symptom (GLIBC error) occur (i.e., typically when installing pytorch with `pip` or `conda`).

2024-01-12 02:36 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/0.create_conda_env.sh
> +
Nits: remove excess blank lines at the end of script.

2024-01-12 02:37 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/1.prepare_data.sh
Do we need this shell script? It's just one-liner.

2024-01-12 02:40 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/exec_torchrun.sh
> +export GPUS_PER_NODE=8
Nits: this is hardcoded, so put a comment? Otherwise, consider to probe env var `SLURM_GPUS_ON_NODE` (reference: #71)

2024-01-12 02:41 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/exec_torchrun.sh
> +MASTER_NODE=$(scontrol show hostname | head -n 1)
Or just `MASTER_NODE=$(hostname)` ?

Reference: https://slurm.schedmd.com/sbatch.html#SECTION_DESCRIPTION

> When the job allocation is finally granted for the batch script, Slurm runs a single copy of the batch script on the first node in the set of allocated nodes.

2024-01-12 02:43 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/prepare_dataset.py
> +from functools import partial
Nits: all import on top of this file?

2024-01-12 02:43 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/prepare_dataset.py
> +training_input_path = f'processed/data/'
Nits: double quote.

2024-01-12 02:46 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/scripts/train.py
> +try:
Consider to add a comment to this stanza, that this is the only changes added to a vanilla FSDP training, to enable smddp collective

2024-01-12 02:48 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/README.md
Somewhere in this file, allude what are the few liners (i.e., minimum changes) to add to a vanilla FSDP training, to convey to users what it takes to use smddp collectives in their training script..

2024-01-12 02:49 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/README.md
Even better to link to the lines in the `train.py`.

2024-01-12 02:50 UTC, verdimrc commented on 3.test_cases/13.SM-dataparallel-deepspeed/0.create_conda_env.sh
> +
Add a comment to explain where conda & mamba will be installed

2024-01-12 02:51 UTC, verdimrc commented on 3.test_cases/13.SM-dataparallel-deepspeed/README.md
All comments or reviews from `12.SM-dataparallel-FSDP` are applicable to this version too.

2024-01-12 02:52 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/README.md
> +### Required Dependencies of SMDDP Library
Add an overview sentence so users have some idea, what's already pre-baked in HyperPod (is it CUDA?), and what else to install.

2024-01-12 02:53 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/0.create_conda_env.sh
> +
Add a comment to explain where conda & mamba will be installed

2024-01-12 02:54 UTC, verdimrc commented on 3.test_cases/13.SM-dataparallel-deepspeed/exec_torchrun.sh
Same comments from FSDP version.

2024-01-12 02:55 UTC, verdimrc commented on 3.test_cases/13.SM-dataparallel-deepspeed/code/train.py
Same comments from FSDP version.

2024-01-12 02:56 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/scripts/train.py
> +    parser.add_argument("--model_dir",type=str,default="/opt/ml/model")
What's the permission of `/opt/ml/model`?

If you want to retain this default, put a comment why you choose this as the default path (is it for compatibility with SageMaker Training?).

2024-01-12 02:56 UTC, verdimrc requested changes
Please address comments. @ruhanprasad

2024-01-18 22:35 UTC, ruhanprasad commented on 3.test_cases/12.SM-dataparallel-FSDP/README.md
> +You will need a slurm cluster with a shared parallel filesystem such as [Amazon FSx for Lustre](https://docs.aws.amazon.com/fsx/latest/LustreGuide/getting-started.html).  See the sagemaker-hyperpod s
I meant the hyperpod folder of the repo; changing to `[SageMaker Hyperpod](1.architectures/5.sagemaker-hyperpod)` for more clarity

2024-01-19 01:30 UTC, ruhanprasad commented on 3.test_cases/12.SM-dataparallel-FSDP/1.prepare_data.sh
Removed it and added instruction to just run the one-line to prepare the dataset.

2024-01-19 01:31 UTC, ruhanprasad commented on 3.test_cases/12.SM-dataparallel-FSDP/exec_torchrun.sh
> +export GPUS_PER_NODE=8
Added comment; this example uses the SMDDP library which only works on P4d/P4de instances (which have 8 GPUs per node).

2024-01-19 01:44 UTC, ruhanprasad commented on 3.test_cases/12.SM-dataparallel-FSDP/exec_torchrun.sh
> +MASTER_NODE=$(scontrol show hostname | head -n 1)
I was given this line by a hyperpod engineer. I believe this line is executed on the cluster headnode but we want the hostname of one of the compute nodes hence the use of `scontrol`

2024-01-19 23:13 UTC, ruhanprasad commented on 3.test_cases/12.SM-dataparallel-FSDP/scripts/train.py
> +    parser.add_argument("--model_dir",type=str,default="/opt/ml/model")
Removed this argument altogether, it wasn't actively being used in the scripts

2024-01-22 01:40 UTC, verdimrc approved these changes

2024-01-22 01:42 UTC, verdimrc commented on 3.test_cases/12.SM-dataparallel-FSDP/README.md
> +To launch the distributed training job, run `sbatch 1.run_training.sbatch`.   By default the number of nodes in the job is 2, but this can be changed in the `#SBATCH --nodes=...` argument in the sbat
```suggestion
To launch the distributed training job, run `sbatch 1.run_training.sbatch`.  By default the number of nodes in the job is 2, but this can be changed either by (i) editing the sbatch script to change the `#SBATCH --nodes=...` argument, or (ii) run `sbatch --nodes=... 1.run_training.sbatch` to override the number of nodes in the sbatch script.
```

2024-01-22 01:43 UTC, verdimrc commented on 3.test_cases/13.SM-dataparallel-deepspeed/README.md
> +No dataset preparation is needed as this example uses synthetic data for simplicity.  To launch the distributed training job, run `sbatch 1.run_training.sbatch`.  By default the number of nodes in th
```suggestion
No dataset preparation is needed as this example uses synthetic data for simplicity. To launch the distributed training job, run `sbatch 1.run_training.sbatch`. By default the number of nodes in the job is 2, but this can be changed either by (i) editing the sbatch script to change the `#SBATCH --nodes=...` argument, or (ii) run `sbatch --nodes=... 1.run_training.sbatch` to override the number of nodes in the sbatch script.
```

2024-01-22 01:47 UTC, verdimrc commented
@perifaws : over to you to finalize review.

2024-01-23 00:39 UTC, perifaws approved these changes

2024-01-23 00:39 UTC, merged